## Linear Algebra
Fecha: 30/12/2024
Tema: Algebra Lineal, Derivadas, Funciones

In [3]:
# Vamos a llamar a dos librerias con las que vamos a trabajar:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Vamos a crear un vector:
vector1 = np.array([3,4,5]) # Se que es un vector porque tiene solo un bracket recto
vector1

array([3, 4, 5])

In [5]:
# Como identificar un vector:
vector1.shape # Es un vector porque tiene la forma (numero de elementos, )

(3,)

In [6]:
# Los vectores se pueden sumar
vector1 + 1 # Por Broadcasting añade el 1 a cada elemento del vector.

array([4, 5, 6])

In [7]:
# Ese uno se le asigno a cada elemento del vector. Y esta operacion se llama broadcasting

In [8]:
# De igual manera sucede con la multiplicacion
vector1 * 0.5 #numby detecta el tipo de datos y convierte si fuera necesario

array([1.5, 2. , 2.5])

# ME FUI A DORMIR A BENJA. QUEDE A LA HORA Y 15 MINS APROX DE LA CLASE.

In [9]:
# Vamos a generar una MATRIZ DE 3 FILAS Y 2 columnas
array1 = np.array([[3,1], [4,1], [1,1]])
array1

array([[3, 1],
       [4, 1],
       [1, 1]])