## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.
Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).  
*For example, the probability of an even die roll is 3/6 = 1/2.*

In [66]:
import random # Generador de Numeros aleatoreos. 
#Traigo una libreria de numeros aleatorios. No se le pone alias ya que suele generar confusiones.

In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
# GENERACION DE LANZAMIENTO DE UNA MONEDA, SELLO = 0, CARA = 1):
toss = random.randint(0,1)  #Randint traera de manera aleatoria un 0 o un 1
toss

0

In [69]:
# AHORA DE MANERA PROGRAMATICA, HAREMOS EL LANZAMIENTO DE LA MONEDA 10 VECES. 
# SERA UNA GENERACION DE LANZAMIENTO DE MONEDAS, CON UNA ESTRUCTURA DE CONTROL (for, if, while)
toss_results = [] # creamos una lista vacia
for i in range(10): # hago 10 intentos
    result = random.randint(0,1) # el resultado puede ser 0 0 1
    toss_results.append(result) #vamos agregando a la lista el resultado de cada tirada
print(toss_results)

[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]


In [70]:
# COMO HAGO QUE UN LANZAMIENTO DE MONEDAS SEA UN EVENTO CONTROLADO Y REPRODUCIBLE. 
# HAREMOS UNA GENERACION DE LANZAMIENTO DE MONEDAS, CONTROLADO PARA SER REPRODUCIBLE. 
# SI SALE UN RESULTADO A MI, A CUALQUIER OTRA PERSONA QEU USE MIS MISMAS LIBRERIAS LE 
# SALDRA EL MISMO RESULTADO Y SERA DE ESTA FORMA COMPARABLE. 
random.seed(2024)  # escuchar minuto 10 que quiere decir esta linea.
toss_results = [] # creamos una lista vacia
for i in range(10): # hago 10 intentos
    result = random.randint(0,1) # el resultado puede ser 0 0 1
    toss_results.append(result) #vamos agregando a la lista el resultado de cada tirada
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [71]:
# CUAL ES LA PROBABILIDAD DE QUE ME SALGA CARA O SELLO ? 
# EL NUMERO DE CASOS FAVORABLES DE QUE SALGA CARA, SERA IGUAL AL NUMERO DE CASOS FAVORABLES DE QUE SALGA SELLO.
# CALCULAR LA PROBABILIDAD DE QEU SALGA CARA EN 10 LANZAMIENTOS DE MONEDA
toss_results = [] # creamos una lista vacia
for i in range(100): # hago 100 intentos
    result = random.randint(0,1) # el resultado puede ser 0 0 1
    toss_results.append(result) #vamos agregando a la lista el resultado de cada tirada
# print(toss_results) # por ahora no lo usamos

sum(toss_results)/len(toss_results) #calcula la probabilidad de que salga 1 en las 100 tiradas. 

0.48

In [72]:
# cada vez que corra el codigo anterior me dara un valor diferente.
# Si incrementamos el rango a 1000: veremos que cada vez que corro el codigo me dara un valor mas cercano a 0.50
toss_results = [] # creamos una lista vacia
for i in range(1000): # hago 100 intentos
    result = random.randint(0,1) # el resultado puede ser 0 o 1
    toss_results.append(result) #vamos agregando a la lista el resultado de cada tirada
# print(toss_results) # por ahora no lo usamos

sum(toss_results)/len(toss_results) #calcula la probabilidad de que salga 1 en las 100 tiradas. 

0.49

In [73]:
# Quiere decir que la probabilidad de un evento es el resultado esperado de una generacion aleatoria de eventos 
# que lo ejecutamos infinitasveces. 
# Si corremos infinitasveces el experimeto, llegariamos a la probabilidad esperada. en este caso 0.50

In [74]:
# Cual es la probabilidad de sacar 1 o 2 en un lanzamiento de dados?
# Resultados posibles: 6 Asi que el denominador es 6
# Resultados posibles: 2
# 2/6 = 33%

In [75]:
# Traemos otra libreria util:
from fractions import Fraction

In [76]:
# Como represento ganar con tijera en un juego de  piedra papel o tijera?
Fraction(1,3) 
# esta es la representacion de una francion en python. 
# es un tipo de datos creado adhoc, solo para representar fracciones.

Fraction(1, 3)

In [77]:
#2. CALCULAR LA PROBABILIDAD DE SACAR PAR EN UN LANZAMIENTO DE DADOS
# Generamos un Conjunto (estructura o coleccion de datos llamado set en python)
# Nuestros resultados exitosos serian even. Los conjuntos los creamos con parentecis curvos.
even = {2,4,6}
points = {1,2,3,4,5,6} # posibles resultados de un dado. Asumimos que el dado esta perfectamente balanceado.
set.intersection(even, points) # Nos dice la interseccion de even y points. los numeros comunes en ambos conjuntos
# DEFINO LA FUNCION PROBABILIDAD:
def Pr(event, space): # en matematica la probabilidad se anota con p mayuscula.
    return Fraction(len(set.intersection(event, space)),len(space)) 
# len me da lo cantidad de elementos en una coleccion, 
# len me da la interseccion de los eventos favorables.
# abajo len de los casos posibles. 

In [78]:
Pr(even, points)

Fraction(1, 2)

In [79]:
# CALCULAR LA PROBABILIDAD DE OBTENER 5 O 6 EN UN LANZAMIENTO DE DADOS
success = {5,6}
points = {1,2,3,4,5,6}
Pr(success, points)

Fraction(1, 3)

THIS REFERS TO A DISCRETE SAMPLE SPACE. SO THE PROBABILITY IS RELATED TO A DISCRETE EVENT.  

In [80]:
# QUE CAJA ESCOGIO PEPE SI QUIERE OBTENER UN 1:
# box1 = [1,0,0,0] la probabilidad de exito es 1/4 = 0.25
# box2 = [1,1,0,0,0] la probabilidad de exito es 2/5 = 0.4
# pepe debe elegir la caja 2
# haremos esto abajo, representado como un vector

box1 = np.array([1,0,0,0]) # Sabemos que es un vector ya que tiene solo estos parentesis ([])
np.random.choice(box1, 1)  # Simula el evento de sacar una piedra. 
# Cada vez que lo corra me dara un 1 o un 0 aleatoreamente.

array([0])

In [81]:
trial = np.random.choice(box1, 10000) # aca tiramos 10000 para ver si sale 1 o 0
trial.mean() #nos dice la proporcion de que salga 1
# en el infinito la probabilidad se acercara al 0.25 que calculamos arriba

np.float64(0.2524)

In [82]:
box2 = np.array([1,0,1,0,0]) # el orden de los 1 y 0 da igual
trial = np.random.choice(box2, 100000)
trial.mean() #aqui funciona mean porque solo hay dos resultados 0, y 1, y ademas el resultado exitoso es 1 solo. 
# en el infinito la probabilidad se acercara al 0.40 que calculamos arriba


np.float64(0.39953)

In [83]:
# Cuando son mas de dos resultados, ejemplo piedra papel o tijera usamos:
success = np.isin(trial, [1])
probability = len(trial[success]) / len(trial)
probability

0.39953

In [84]:
# Hareos de ejemplo piedra papel o tijera. En pero se llama "yankenpo"
np.random.seed(2024) 
# La linea de arriba permite controlar que a todos los compañeros nos salga el mismo resultados, bajo las mismas condiciones.  
# Lo que hace es dejar fijo los resultados del primer intento. 
# Ponemos 2024 como un numero aleatoreo. por eso es importante el tema de la reproducibilidad. 
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo, 10)
success = np.isin(trial, [2]) # Asumimos que el exito es sacar tijera que lo represento con el nro dos. isin me da un vector de booleanos. Es una operacion logica.
probability = len(trial[success]) / len(trial)
probability

0.2

In [85]:
yankenpo

array([1, 2, 3])

In [86]:
trial # esta compuesto por los resultados

array([1, 3, 1, 1, 1, 3, 2, 2, 1, 3])

In [87]:
success # esta compuesto por si le acertaste o no en cada tirada.

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [88]:
trial[success] # esto es una mascara (vector de booleanos dentro de los braquets rectos que afecta al vector)
# Solo me devuelve los casos existosos, donde la mascara era true. es como un filtro

array([2, 2])

In [89]:
# Juego de cartas donde ganas si sacas 21. Digamos que los resultados fueron asi:
# 14, 22 , 21, 15 18,23,19
result = np.array([14,22,21,15,18,23,19])
success = np.isin(result, [21])
result[success] #filtramos los casos existosos. (filtramos los casos exitosos)

array([21])

In [90]:
#3. EL SIGUIENTE PROBLEMA MUESTRA LA PROBABILIDAD CONDICIONAL
# CUAL ES LA PROBABILIDAD DE SACAR UN As EN UNA SEGUNDA EXTRACION, YA SAQUE UN As.
# cuantos Ases hay en una baraja: 4
# Cuantos Naipes hay en una baraja: 52
# Cual es la probabilidad de sacar en la primera extracion un As: 4/52 = 1/13
# Si ya saque un As de la Baraja, cuantos naipes me quedan ? 51 y 3 Ases
# Cual seria la probabilidad de sacar un As en la segunda extracion, dado que saque un As en la primera extracion ? y esto se escribe de esta forma: 
# Pr(sacar As en segunda extracion | Salio As en primer extracion)  Pr (A | B) = Probabilidad de A dado B
# Por lo tanto esto quiere decir que esta probabilidad esta condicionada al evento de sacar un As en la primera extracion.
# La formula para calcularlo seria Pr = 3/51

In [91]:
# Importante Aprender estas Formulas:
# Formula 1: Pr(A and B) = Pr(A)*Pr(B|A)
# Formula 2: Si A y B son independientes entonces Pr(A|B) = Pr(A)  (Cuidado!!!: con asumir independencia cuando no la hay)
# Formula 3: Regla de la cadena: Pr(A and B and C) = Pr(A)*Pr(B|A)*Pr(C|A and C) 
# Formula 4: Regla de Adicion: Pr(A or B) = Pr(A) + Pr(B) - Pr (A and B)

In [92]:
# Ejemplo1:
# En un avion hay 3 bombas, cada bomba tiene 0.4 probabilidades de explotar. Cual es la probabilidad de que la segunda bomba explote?
# La probabilidad de que explote cada bomba es independiente de que explote la otra? 
# Es decir para que explote una, no es una condicion que explote otra. 
# Cual es la probabilidad de que las tres exploten a la vez ? 0.4 * 0.4 * 0.4 

In [ ]:
# Ejemplo2:
# Cual es la probabilidad de que en una sala con 10 personas dos cumplan años el mismo dia?
# Y en una sala con 20 personas?
# Y con una sala con 30 personas?
# Y en una sala con 50 personas? 

#Usaremos NumPy para resolverlo.

# Definimos una funcion:

# ME QUEDE EN EL MINUTO 30 DE LA SEGUNDA PARTE DE LA CLASE 8